name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    concurrency: production
    environment:
      name: 'blooblah'
      url: format('https://google.com{0}','/maps')
    steps:
      - name: deploy
        id: deploy-google
        run: echo "hello world"