name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    concurrency: production
    env:
      test_url: ${{ format('https://google.com{0}','/maps') }}
    environment:
      name: 'blooblah'
      url: $test_url
    steps:
      - name: deploy
        id: deploy-google
        run: echo "hello world"