name: Deployment

on:
  push:
    branches:
      - main
      - tst

jobs:
  deployment:
    runs-on: ubuntu-latest
    concurrency: production
    env:
      test: test
    environment:
      name: ${{ GITHUB_SHA }}
      url: ${{ format('https://google.com{0}','/maps') }}
    steps:
      - name: deploy
        id: deploy-google
        run: |
          echo "hello world"
          echo "setting release identifier to ${GITHUB_SHA:0:8}"
          echo "sha=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT

