name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    concurrency: production
    environment:
      name: 'production'
      url: 'google.com'
    steps:
      - name: deploy
        id: deploy-google
        run: echo "hello world"