name: Deployment

on:
  push:
    branches:
      - main
      - tst

jobs:
  deployment:
    runs-on: ubuntu-latest
    concurrency: production
    environment:
      name: ${GITHUB_SHA:0:8}
      url: ${{ format('https://google.com{0}','/maps') }}
    steps:
      - name: deploy
        id: deploy-google
        run: echo "hello world"